# Generated by Django 5.0.12 on 2025-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
