# Generated by Django 5.0.12 on 2025-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmethod_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
