# Generated by Django 5.0.12 on 2025-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentmethod_last4_alter_paymentmethod_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
