# Generated by Django 5.0.12 on 2025-02-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_user_city_user_phone_number_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
    ]
