# Generated by Django 5.0.12 on 2025-04-08 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_belongs_fav_sensor"),
        ("users", "0008_alter_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_sensor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="sensors.sensor",
            ),
        ),
    ]
