# Generated by Django 5.0.12 on 2025-04-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
