# Generated by Django 5.0.12 on 2025-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
