# Generated by Django 5.0.12 on 2025-04-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_latitude_sensor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
