# Generated by Django 5.0.12 on 2025-04-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_belongs_fav_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="belongs",
            name="sensor_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
