# Generated by Django 5.0.12 on 2025-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
