# Generated by Django 5.0.12 on 2025-04-22 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='conversation_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
