# Generated by Django 5.0.12 on 2025-04-22 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_friendship_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
