# Generated by Django 5.1.6 on 2025-02-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreItem',
            new_name='Product',
        ),
    ]
