web: python manage.py migrate && gunicorn config.wsgi:application --workers 1 --bind 0.0.0.0:8000
worker: celery -A config.celery_app worker --loglevel=info
beat: celery -A config.celery_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler